# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /mnt/drivetwo/Programs/Linux_Unreal_Engine_5.7.4

TARGETS = \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	ProjetAnglais-Android-DebugGame  \
	ProjetAnglais-Android-Development  \
	ProjetAnglais-Android-Shipping  \
	ProjetAnglais-Linux-DebugGame  \
	ProjetAnglais-Linux-Development  \
	ProjetAnglais-Linux-Shipping  \
	ProjetAnglais-LinuxArm64-DebugGame  \
	ProjetAnglais-LinuxArm64-Development  \
	ProjetAnglais-LinuxArm64-Shipping  \
	ProjetAnglais \
	ProjetAnglaisEditor-Linux-DebugGame  \
	ProjetAnglaisEditor-Linux-Development  \
	ProjetAnglaisEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend ProjetAnglaisEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug ProjetAnglaisEditor-Linux-Debug


LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

ProjetAnglais-Android-DebugGame:
	 $(BUILD) ProjetAnglais Android DebugGame  -Project="/mnt/drivetwo/Projects/UE5/ProjetAnglais/ProjetAnglais.uproject" $(ARGS)

ProjetAnglais-Android-Development:
	 $(BUILD) ProjetAnglais Android Development  -Project="/mnt/drivetwo/Projects/UE5/ProjetAnglais/ProjetAnglais.uproject" $(ARGS)

ProjetAnglais-Android-Shipping:
	 $(BUILD) ProjetAnglais Android Shipping  -Project="/mnt/drivetwo/Projects/UE5/ProjetAnglais/ProjetAnglais.uproject" $(ARGS)

ProjetAnglais-Linux-DebugGame:
	 $(BUILD) ProjetAnglais Linux DebugGame  -Project="/mnt/drivetwo/Projects/UE5/ProjetAnglais/ProjetAnglais.uproject" $(ARGS)

ProjetAnglais-Linux-Development:
	 $(BUILD) ProjetAnglais Linux Development  -Project="/mnt/drivetwo/Projects/UE5/ProjetAnglais/ProjetAnglais.uproject" $(ARGS)

ProjetAnglais-Linux-Shipping:
	 $(BUILD) ProjetAnglais Linux Shipping  -Project="/mnt/drivetwo/Projects/UE5/ProjetAnglais/ProjetAnglais.uproject" $(ARGS)

ProjetAnglais-LinuxArm64-DebugGame:
	 $(BUILD) ProjetAnglais LinuxArm64 DebugGame  -Project="/mnt/drivetwo/Projects/UE5/ProjetAnglais/ProjetAnglais.uproject" $(ARGS)

ProjetAnglais-LinuxArm64-Development:
	 $(BUILD) ProjetAnglais LinuxArm64 Development  -Project="/mnt/drivetwo/Projects/UE5/ProjetAnglais/ProjetAnglais.uproject" $(ARGS)

ProjetAnglais-LinuxArm64-Shipping:
	 $(BUILD) ProjetAnglais LinuxArm64 Shipping  -Project="/mnt/drivetwo/Projects/UE5/ProjetAnglais/ProjetAnglais.uproject" $(ARGS)

ProjetAnglais: ProjetAnglais-Linux-Development

ProjetAnglaisEditor-Linux-DebugGame:
	 $(BUILD) ProjetAnglaisEditor Linux DebugGame  -Project="/mnt/drivetwo/Projects/UE5/ProjetAnglais/ProjetAnglais.uproject" $(ARGS)

ProjetAnglaisEditor-Linux-Development:
	 $(BUILD) ProjetAnglaisEditor Linux Development  -Project="/mnt/drivetwo/Projects/UE5/ProjetAnglais/ProjetAnglais.uproject" $(ARGS)

ProjetAnglaisEditor: ProjetAnglaisEditor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/mnt/drivetwo/Projects/UE5/ProjetAnglais/ProjetAnglais.uproject" -Game 

.PHONY: $(TARGETS)
